import {Sandbox} from 'e2b';
const PROJECT_DIR='/home/user/project'; const ZIP_PATH='/home/user/project.zip';
const MAX_ZIP_BYTES=Number(process.env.MAX_ZIP_BYTES||8388608); const SANDBOX_TIMEOUT_MS=10*60*1000; const COMMAND_TIMEOUT_MS=90*1000;
type S={sandbox:Sandbox;logs:string[];lastUsed:number}; const sessions=new Map<string,S>();
const PY=`import os,zipfile\nsrc="${PROJECT_DIR}"\ndst="${ZIP_PATH}"\nexclude={"node_modules",".git"}\nwith zipfile.ZipFile(dst,"w",zipfile.ZIP_DEFLATED) as z:\n for root,dirs,files in os.walk(src):\n  dirs[:]=[d for d in dirs if d not in exclude]\n  for n in files:\n   p=os.path.join(root,n);z.write(p,os.path.relpath(p,src))\nprint("zipped ok")`;
async function session(id:string){if(!process.env.E2B_API_KEY)throw new Error('E2B_API_KEY is not configured');const ex=sessions.get(id);if(ex){ex.lastUsed=Date.now();await ex.sandbox.setTimeout(SANDBOX_TIMEOUT_MS).catch(()=>{});return ex}const sandbox=await Sandbox.create({timeoutMs:SANDBOX_TIMEOUT_MS});const s={sandbox,logs:[],lastUsed:Date.now()};sessions.set(id,s);return s}
export async function writeFile(buildId:string,p:string,content:string){const s=await session(buildId);const safe=p.replace(/^\/+/, '').replace(/\.\./g,'_');await s.sandbox.files.write([{path:`${PROJECT_DIR}/${safe}`,data:content}]);s.logs.push(`Wrote ${safe}`);return {ok:true,path:safe}}
async function shell(s:S,cmd:string,label:string){try{const r=await s.sandbox.commands.run(`cd ${PROJECT_DIR} && ${cmd}`,{timeoutMs:COMMAND_TIMEOUT_MS});const out=[r.stdout,r.stderr].filter(Boolean).join('\\n').trim();s.logs.push(`$ ${label}${out?'\\n'+out.slice(0,2000):''}`);return (r.exitCode??0)===0}catch(e){s.logs.push(`$ ${label}\\n${e instanceof Error?e.message:String(e)}`);return false}}
export async function finishBuild(buildId:string,setupCommands:string[]=[],zipName='project.zip'){const s=sessions.get(buildId);if(!s)return {ok:false,error:'No files written for this build'};try{for(const c of setupCommands.slice(0,6))await shell(s,c,c);await s.sandbox.files.write([{path:'/home/user/_zip_helper.py',data:PY}]);await s.sandbox.commands.run(`python3 /home/user/_zip_helper.py`,{timeoutMs:COMMAND_TIMEOUT_MS});const info:any=await s.sandbox.files.getInfo(ZIP_PATH).catch(()=>null);if(!info)return {ok:false,error:'Zipping failed',log:s.logs.join('\\n\\n')};if(info.size>MAX_ZIP_BYTES)return {ok:false,error:`ZIP exceeds ${(MAX_ZIP_BYTES/1024/1024).toFixed(1)}MB`,log:s.logs.join('\\n\\n')};const bytes=await s.sandbox.files.read(ZIP_PATH,{format:'bytes'}) as Uint8Array;return {ok:true,fileName:zipName,sizeBytes:bytes.length,zipBytes:bytes,log:s.logs.join('\\n\\n')}}finally{sessions.delete(buildId);s.sandbox.kill().catch(()=>{})}}
